# Generated by Django 4.0.5 on 2022-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_income', models.DateField(auto_now_add=True)),
                ('amount_of_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(auto_now_add=True)),
                ('nameof_product', models.CharField(max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_of_goods', models.IntegerField()),
                ('amount_of_expenses', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
