# Generated by Django 4.0.5 on 2022-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedgoods',
            name='quantity_of_goods',
            field=models.IntegerField(max_length=200000),
        ),
    ]
