# Generated by Django 4.0.5 on 2022-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_purchasedgoods_quantity_of_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedgoods',
            name='quantity_of_goods',
            field=models.IntegerField(),
        ),
    ]
