# Generated by Django 4.0.5 on 2022-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_income_amount_of_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='total_income',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Total income'),
        ),
    ]
