# Generated by Django 4.0.5 on 2022-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_income_total_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedgoods',
            name='nameof_product',
        ),
        migrations.AddField(
            model_name='purchasedgoods',
            name='name_of_product',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of product'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='amount_of_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Amount of expenses'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price per item'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='quantity_of_goods',
            field=models.IntegerField(null=True, verbose_name='Quantity of goods'),
        ),
    ]
