# Generated by Django 4.0.5 on 2022-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_totalexpenses_totalincome_remove_income_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_of_income',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
    ]
