# Generated by Django 4.0.5 on 2022-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_income_date_of_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Amount of expenses')),
                ('date_of_balance', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date')),
            ],
        ),
    ]
