# Generated by Django 4.0.5 on 2022-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_walletbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalincome',
            name='my_date',
            field=models.DateField(auto_now=True),
        ),
    ]
