# Generated by Django 4.0.5 on 2022-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_totalincome_my_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalincome',
            name='my_date',
        ),
        migrations.AddField(
            model_name='totalincome',
            name='total_income_date',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='Date'),
        ),
    ]
