# Generated by Django 4.0.5 on 2022-07-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_totalexpenses_total_expanses_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalExpenses',
        ),
        migrations.DeleteModel(
            name='TotalIncome',
        ),
        migrations.DeleteModel(
            name='WalletBalance',
        ),
    ]
