# Generated by Django 4.0.5 on 2022-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_delete_totalexpenses_delete_totalincome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date_of_income'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterModelOptions(
            name='purchasedgoods',
            options={'ordering': ['-date_of_purchase'], 'verbose_name': 'Purchased good', 'verbose_name_plural': 'Purchased goods'},
        ),
        migrations.RemoveField(
            model_name='purchasedgoods',
            name='amount_of_expenses',
        ),
        migrations.AlterField(
            model_name='income',
            name='amount_of_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount of income'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='name_of_product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of product'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='price_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per item'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='quantity_of_goods',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity of goods'),
        ),
    ]
