# Generated by Django 4.0.5 on 2022-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_income_options_alter_purchasedgoods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='type_of_income',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of income'),
        ),
    ]
