# Generated by Django 4.0.5 on 2022-08-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_category_purchasedgoods_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedgoods',
            name='title',
        ),
    ]
