# Generated by Django 4.0.5 on 2022-09-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_remove_purchasedgoods_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type_of_income',
            field=models.CharField(max_length=255, null=True, verbose_name='Type of income'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='purchasedgoods',
            name='name_of_product',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of product'),
        ),
    ]
